#!/usr/bin/env python3
"""Generates dist/install.luau from dist/modules.json.

Kuik ships as a folder of ModuleScripts rather than a single bundled file --
dist/Kuik.luau can exceed Roblox's 200,000 character Source limit once the
library grows (see tools/build.py, LIMIT = 200_000). This script rebuilds
that folder at install time, from the Studio command bar or a plugin, the
same way Lume's dist/install.luau does.

    python3 tools/build_installer.py
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST = os.path.join(ROOT, "dist")
MODULES_JSON = os.path.join(DIST, "modules.json")
OUTPUT = os.path.join(DIST, "install.luau")

LIMIT = 200_000
VERSION_TOKEN = "%%KUIK_VERSION%%"


def escape(source):
    out = []
    for char in source:
        if char == "\\":
            out.append("\\\\")
        elif char == "\"":
            out.append("\\\"")
        elif char == "\r":
            out.append("\\r")
        elif char == "\n":
            out.append("\\\n")
        else:
            out.append(char)
    return "".join(out)


def version(root_source):
    match = re.search(r'Version\s*=\s*"([^"]+)"', root_source)
    return match.group(1) if match else "0.0.0"


HEAD = '''--!nocheck

--[[
\tKuik installer (generated by tools/build_installer.py -- do not edit)

\tBuilds the library into your place as a folder of ModuleScripts, ready to
\trequire(). dist/Kuik.luau (the single-file bundle) can exceed Roblox's
\t200,000 character Source limit, so this installs the split modules
\tinstead -- same shape as src/, same require(script.X) calls, nothing
\trewritten.

\tStudio command bar (one line):

\t  loadstring(game:GetService("HttpService"):GetAsync("<RAW_URL>/dist/install.luau"))()

\tOptions (set before running, all optional):

\t  _G.KuikInstall = {
\t      parent    = game:GetService("ReplicatedStorage"),  --// where to build
\t      name      = "Kuik",                                --// root instance name
\t      overwrite = true,                                  --// replace an existing install
\t      select    = true,                                  --// select the root when done
\t      silent    = false,                                 --// suppress output
\t  }
]]

local MODULES = {
'''

TAIL = '''}

local LIMIT = 200000

local options = (type(_G.KuikInstall) == "table" and _G.KuikInstall or {}) :: any

local parent = options.parent or game:GetService("ReplicatedStorage")
local name = options.name or "Kuik"
local silent = options.silent == true

local function say(message: string)
\tif not silent then
\t\tprint(message)
\tend
end

local existing = parent:FindFirstChild(name)

if existing then
\tif options.overwrite == false then
\t\twarn(`Kuik: {name} already exists and overwrite is off; nothing was installed`)
\t\treturn
\tend

\texisting:Destroy()

\tsay(`Kuik: replaced the existing {parent:GetFullName()}.{name}`)
end

local byPath = {}

for _, entry in MODULES do
\tlocal path, className, source = entry[1], entry[2], entry[3]

\tif source and #source >= LIMIT then
\t\twarn(`Kuik: {path} is {#source} chars, over the {LIMIT} character Source limit -- regenerate the installer`)
\t\treturn
\tend

\tlocal instance = Instance.new(className)
\tlocal parentPath = string.match(path, "^(.+)/[^/]+$")

\t--// the root honours the `name` option; everything below keeps its own name
\tinstance.Name = if parentPath then string.match(path, "([^/]+)$") else name

\tif source then
\t\t--// Source is only writable from the command bar or a plugin
\t\tlocal ok, err = pcall(function()
\t\t\tinstance.Source = source
\t\tend)

\t\tif not ok then
\t\t\twarn(`Kuik: could not write {path} ({err}). Run this from the Studio command bar or a plugin.`)
\t\t\treturn
\t\tend
\tend

\tinstance.Parent = if parentPath then byPath[parentPath] else parent
\tbyPath[path] = instance
end

local installed = parent:FindFirstChild(name)

if installed then
\tinstalled:SetAttribute("KuikVersion", "''' + VERSION_TOKEN + '''")
\tinstalled:SetAttribute("KuikInstalledAt", os.time())

\tif options.select ~= false then
\t\tlocal Selection = game:GetService("Selection")

\t\tpcall(function()
\t\t\tSelection:Set({ installed })
\t\tend)
\tend
end

say(`Kuik installed to {parent:GetFullName()}.{name} ({#MODULES} instances)`)
'''


def main():
    with open(MODULES_JSON, encoding="utf-8") as handle:
        modules = json.load(handle)

    if "" not in modules:
        sys.exit("dist/modules.json is missing the root module (\"\")")

    root_version = version(modules[""])

    pieces = [HEAD]

    for key in sorted(modules, key=lambda name: (name != "", name)):
        path = "Kuik" if key == "" else "Kuik/" + key
        source = escape(modules[key])
        pieces.append('{"%s","ModuleScript","%s"},\n' % (path, source))

    pieces.append(TAIL)

    output = "".join(pieces).replace(VERSION_TOKEN, root_version)

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(output)

    print("%d modules -> dist/install.luau, %d chars, version %s"
          % (len(modules), len(output), root_version))

    biggest = max(modules.items(), key=lambda pair: len(pair[1]))
    print("largest module: %s at %d chars (limit %d)"
          % (biggest[0] or "init", len(biggest[1]), LIMIT))


if __name__ == "__main__":
    main()
